config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get "blog" => 'static_pages#blog'
  get "static_pages/home"

  resources :products,      only: [:show]
  resources :brands,        only: [:show]
  resources :catalogs,      only: [:show]
  resources :line_items,    only: [:create, :show, :destroy]
  resources :carts,         only: [:create, :update, :new, :show, :destroy]
  resources :orders,        only: [:create, :update, :new, :destroy]
  resources :blog_posts,     only: [:show, :index]

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :products
  accepts_nested_attributes_for :products

  validate :name, presence: true, uniqueness: {case_sensitive: false }
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items

  def add_product product_id
    current_item = line_items.find_by(product_id: product_id)
    if current_item
      current_item.count += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end
end

app/models/catalog.rb
class Catalog < ActiveRecord::Base
  has_many :products
  validate :name, presence: true
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
  belongs_to :order
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items
  has_many :products, through: :line_items
  PAYMENT_TYPES = ["Курьерская доставка по Москве(бесплатно)","Самовывоз(беспалатно)"]

  accepts_nested_attributes_for :line_items

  validates :user_name, :email, :phone, :address , presence: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :visit_products, dependent: :destroy
  has_many :line_items, dependent: :destroy
  has_many :orders, through: :line_items

  belongs_to :brand
  belongs_to  :catalog

  validates :name, presence: true, uniqueness: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}

  mount_uploader :image, ProductUploader
  validate :name, presence: true, uniqueness: {case_sensitive: false }
end

app/models/visit_product.rb
class VisitProduct < ActiveRecord::Base
  belongs_to :product
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  def show
    @post = BlogPost.find(params[:id])
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def index
  end

  def show
    @brand = Brand.find(params[:id])
    @products = @brand.products
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CurrentCart

  before_action :set_cart, only: [:show, :edit,:update, :destroy]

  def show
    @order = Order.new
  end

  def create
  end

  def edit
  end

  def new
  end

  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :ok }
    end
  end
end

app/controllers/catalogs_controller.rb
class CatalogsController < ApplicationController
  def index
  end
  def show
    @catalog = Catalog.find(params[:id])
    @products = @catalog.products
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include CurrentCart
  before_action :set_cart

  def create
    @order = Order.new(order_params)
    @order.add_line_items_from_cart(@cart)
    if @order.save
      Cart.destroy(session[:cart_id])
      session[:cart_id] = nil
      redirect_to root_path
    else
      render 'carts/show'
    end
  end

  def edit
    @line_items = LineItem.find_by_order_id(params[:id])
  end

  private
  def order_params
    params.require(:order).permit(:user_name, :address, :email, :pay_type, :phone)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  end

  def show
    @product = Product.find(params[:id])
    if @product.active
      create_visit_products
    else
      raise ActiveRecord::RecordNotFound
    end
  end

  def new
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def create_visit_products
      VisitProduct.create(product_id: @product.id, sessionid: request.session_options[:id])  if user_not_visit_product(@product, request.session_options[:id])
  end

  def user_not_visit_product product, user
    return true if VisitProduct.where(product_id: product.id, sessionid: user).empty?
    false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def goods_visit_list
    VisitProduct.where(sessionid: request.session_options[:id]).limit(12)
  end

  def brands_list
    Brand.all
  end

  def number_to_rubel price
    number_to_currency(price, unit: "руб.", separator: ".", delimiter: " ", format: "%n %u")
  end

  def catalog_list
    catalogs = Catalog.all
    catalog_has_products? catalogs
  end


  def catalog_has_products? catalogs
    catalogs.delete_if do |catalog|
       true unless catalog_show? catalog
    end
  end



  def child_catalog catalog
    if child_catalog = Catalog.where(parent_id: catalog.id)
      child_catalog
    end
  end

  def catalog_show? catalog
    if catalog_has_product? catalog
     return true
    else
      has_child_and_child_has_product? catalog
    end
  end

  def catalog_has_product? catalog
    catalog.products.empty? ? false : true
  end

  def has_child_and_child_has_product? catalog
    if catalog_has_child? catalog
      return  child_has_product? catalog
    end
    false
  end

  def catalog_has_child? catalog
    Catalog.where(parent_id: catalog.id).empty? ? false : true
  end

  def child_has_product? catalog
    result = false
    children = child_catalog catalog
    children.each do |child|
      result = result || catalog_has_product?(child)
    end
    result
  end

end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/catalogs_helper.rb
module CatalogsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/blog_posts/show.html.haml
%h1= @post.title
%p= @post.created_at.strftime("%d.%m.%Y")
%p
%div= @post.full_description

app/views/brands/_brand.html.haml
- unless brands_list.empty?
  #all_brands
    %h2 Все бренды:
    - brands_list.each do |brand|
      = link_to("#{brand.name}(#{brand.products.count})", brand_path(brand))

app/views/brands/index.html.haml
%h1 Brands#index
%p Find me in app/views/brands/index.html.haml

app/views/brands/show.html.haml
%h1= @brand.name
%ul.products
  - @products.each do |product|
    = render partial: 'products/product_in_list', locals: {product: product}

app/views/carts/create.html.haml
%h1 Carts#create
%p Find me in app/views/carts/create.html.haml

app/views/carts/edit.html.haml
%h1 Carts#edit
%p Find me in app/views/carts/edit.html.haml

app/views/carts/new.html.haml
%h1 Carts#new
%p Find me in app/views/carts/new.html.haml

app/views/carts/show.html.haml
= simple_form_for @order do |f|
  .cart_form
    %h1 В корзине
    = link_to "Delete", cart_path(@cart), method: :delete
    %table#purchases
      %tbody
        -@cart.line_items.each do |line_item|
          %tr{"data-item-id" => line_item.id}
            %td.image
              = link_to image_tag(line_item.product.image_url(:thumb)), product_path(line_item.product)
            %td.name
              = link_to line_item.product.name, product_path(line_item.product)
            %td.price
              = number_to_rubel line_item.product.price
            %td.amount
              %select
                %option{:value => line_item.count, :selected => true}= line_item.count
                -(1..50).each do |i|
                  %option{:value => i}= i
            %td.remove
              = link_to image_tag('delete.png'), line_item_path(line_item), method: :delete, data: {confirm: "Вы уверены?" }
    %h2 Выберите способ доставки:
    %ul#deliveries
      %li
        = f.radio_button :pay_type, Order::PAYMENT_TYPES
        = f.label "Курьерская доставка по Москве (бесплатно)"
        .description
          %p
            %span Курьерская доставка осуществляется на следующий день после оформления заказа, если товар есть в наличии. Курьерская доставка осуществляется в пределах Томска и Северска ежедневно с 10.00 до 21.00. Заказ на сумму свыше 300 рублей доставляется бесплатно.&nbsp;<br><br>Стоимость бесплатной доставки раcсчитывается от суммы заказа с учтенной скидкой. В случае если сумма заказа после применения скидки менее 300р, осуществляется платная доставка.&nbsp;<br><br>При сумме заказа менее 300 рублей стоимость доставки составляет от 50 рублей.
      %li
        = f.radio_button :pay_type, Order::PAYMENT_TYPES
        %h3
          = f.label "Самовывоз (бесплатно)"
        .description
          .p Удобный, бесплатный и быстрый способ получения заказа.
          .pАдрес офиса: Адрес офиса: Москва, ул. Арбат, 1/3, офис 419

    = f.input :user_name, label: 'Имя, фамилия'
    %br
    = f.input :email, label: 'Email'
    %br
    = f.input :phone, label: 'Телефон'
    %br
    = f.input :address, label: 'Адрес доставки'
    %br
    = f.submit 'Оформить заказ', class: 'button'

app/views/catalogs/_catalog_in_blog.html.haml
-unless catalog_list.empty?
  #catalog_menu
    %ul
      - catalog_list.each do |catalog|
        - unless catalog.parent_id
          %li
            = link_to catalog.name, catalog_path(catalog)
            -if child_catalog(catalog)
              %ul
                - child_catalog(catalog).each do |child|
                  - if catalog_has_product? child
                    %li= link_to(child.name, catalog_path(child))

app/views/catalogs/show.html.haml
%h1= @catalog.name
%ul.products
  - @products.each do |product|
    = render partial: 'products/product_in_list', locals: {product: product}

app/views/products/_discount.html.haml
- if discount_products.present?
  %h1 Акционные товары
  %ul.tiny_products
    - discount_products.each do |product|
      = render partial: "products/product_showcase", locals: {product: product}

app/views/products/_price.html.haml
%table
  %tbody
    %tr.variant
      %td
      %td
      %td
        %span.price
          = number_to_currency(product.price, unit: "руб.", separator: ".", delimiter: " ", format: "%n %u")
          %span.currency
=button_to  'в корзину', line_items_path(product_id: product), class: 'button', remote: true

app/views/products/_product_in_list.html.haml
%li.product
  .image= link_to(image_tag(product.image_url(:medium)), product_path(product))
  .product_info
    %h3= link_to product.name, product_path(product)
    .annotation= product.short_description
    =render partial: 'products/price', locals: {product: product}

app/views/products/_product_showcase.html.haml
%li.product
  .image= link_to(image_tag(product.image_url(:medium)), product_path(product))
  %h3= link_to(product.name, product_path(product))
  =render partial: 'products/price', locals: {product: product}

app/views/products/_recommend.html.haml
- if products.present?
  %h1 Рекомендуемые товары
  %ul.tiny_products
    - products.each do |product|
      = render partial: "products/product_showcase", locals: {product: product}

app/views/products/_visit.html.haml
- unless goods_visit_list.empty?
  %h2 Вы просматривали:
  %ul#browsed_products
    - goods_visit_list.each do |product|
      %li= link_to image_tag(product.product.image_url(:thumb)), product_path(product.product)

app/views/products/destroy.html.haml
%h1 Products#destroy
%p Find me in app/views/products/destroy.html.haml

app/views/products/edit.html.haml
%h1 Products#edit
%p Find me in app/views/products/edit.html.haml

app/views/products/index.html.haml
%h1 Products#index
%p Find me in app/views/products/index.html.haml

app/views/products/new.html.haml
%h1 Products#new
%p Find me in app/views/products/new.html.haml

app/views/products/show.html.haml
= provide :title, @product.name
%h1= @product.name
.product
  .image
    =  link_to(image_tag(@product.image_url(:large)), product_path(@product))
  .description
    = @product.full_description
    %p
    =render partial: 'price', locals: {product: @product}

app/views/products/update.html.haml
%h1 Products#update
%p Find me in app/views/products/update.html.haml